services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: notasdb
      POSTGRES_USER: notas_user
      POSTGRES_PASSWORD: StrongPass123!
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/notasdb  # Â¡IMPORTANTE!
      DB_USERNAME: notas_user
      DB_PASSWORD: StrongPass123!
    ports:
      - "8080:8080"
    depends_on:
      - postgres